package com.wgblackmon.aihealthcare.infrastructure.delivery;

import com.wgblackmon.aihealthcare.domain.port.outbound.DailySummaryPort;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Optional;

/**
 * Reads daily article summary files generated by {@link NotebookLMService}
 * from the configured summaries directory.
 *
 * <p>Files follow the naming convention {@code yyyy_MM_dd.html} and
 * {@code yyyy_MM_dd.txt}, written daily by the NotebookLM export pipeline.
 *
 * @author  Bill Blackmon
 * @version 1.0
 * @since   2026-07-20
 * @updated 2026-07-21
 */
@Slf4j
@Component
public class NotebookLMSummaryAdapter implements DailySummaryPort {

    private static final DateTimeFormatter DATE_FORMAT =
            DateTimeFormatter.ofPattern("yyyy_MM_dd");

    private final String summariesDirectory;

    public NotebookLMSummaryAdapter(
            @Value("${aihealthcare.notebooklm.summaries-directory:NotebookLMDirectory/summaries}") String summariesDirectory) {
        log.debug("NotebookLMSummaryAdapter() | summariesDirectory={}", summariesDirectory);
        this.summariesDirectory = summariesDirectory;
    }

    @Override
    public Optional<String> getHtmlSummary(LocalDate date) {
        log.debug("getHtmlSummary() | date={}", date);
        Optional<String> result = readFile(date, ".html");
        log.debug("getHtmlSummary() | return={}", result.isPresent() ? result.get().length() + " chars" : "empty");
        return result;
    }

    @Override
    public Optional<String> getTextSummary(LocalDate date) {
        log.debug("getTextSummary() | date={}", date);
        Optional<String> result = readFile(date, ".txt");
        log.debug("getTextSummary() | return={}", result.isPresent() ? result.get().length() + " chars" : "empty");
        return result;
    }

    @Override
    public Optional<LocalDate> findMostRecentSummaryDate() {
        log.debug("findMostRecentSummaryDate() | (no args)");

        LocalDate today = LocalDate.now();
        int lookbackDays = 30;

        for (int i = 1; i <= lookbackDays; i++) {
            LocalDate candidate = today.minusDays(i);
            String filename = candidate.format(DATE_FORMAT) + ".html";
            Path file = Paths.get(summariesDirectory).resolve(filename);
            if (Files.exists(file)) {
                log.debug("findMostRecentSummaryDate() | return={}", candidate);
                return Optional.of(candidate);
            }
        }

        log.debug("findMostRecentSummaryDate() | return=empty (no files in last {} days)", lookbackDays);
        return Optional.empty();
    }

    private Optional<String> readFile(LocalDate date, String extension) {
        log.debug("readFile() | date={}, extension={}", date, extension);
        String filename = date.format(DATE_FORMAT) + extension;
        Path file = Paths.get(summariesDirectory).resolve(filename);

        if (!Files.exists(file)) {
            log.debug("readFile() | file not found: {}", file);
            log.debug("readFile() | return=empty");
            return Optional.empty();
        }

        try {
            String content = Files.readString(file, StandardCharsets.UTF_8);
            log.debug("readFile() | return={} chars", content.length());
            return Optional.of(content);
        } catch (IOException e) {
            log.warn("readFile() | failed to read {}: {}", file, e.getMessage());
            log.debug("readFile() | return=empty (IOException)");
            return Optional.empty();
        }
    }
}
