package com.wgblackmon.aihealthcare.domain.model;

import java.time.Instant;
import java.util.List;

/**
 * Immutable domain record representing a competitive intelligence report
 * generated on demand for a company or market segment.
 *
 * <p>Each report is the product of a COMBINED research pipeline run followed
 * by a deep-dive AI synthesis. The {@code htmlContent} contains a structured
 * analysis with executive summary, market position, strengths/weaknesses,
 * recent developments, competitive landscape, and outlook sections.
 *
 * @param reportId    Unique identifier (UUID).
 * @param query       The free-form query that triggered this report.
 * @param htmlContent Full HTML report content generated by the AI.
 * @param sourceCount Number of source citations used in the report.
 * @param userEmail   Email of the user who triggered generation.
 * @param generatedAt Timestamp when the report was generated.
 * @param sources     Source citations used to produce this report (may be empty for legacy reports).
 *
 * @author  Bill Blackmon
 * @version 1.0
 * @since   2026-08-03
 * @updated 2026-08-03
 */
public record IntelReport(
        String reportId,
        String query,
        String htmlContent,
        int sourceCount,
        String userEmail,
        Instant generatedAt,
        List<SourceCitation> sources
) {

    /**
     * Compact constructor — validates required fields.
     */
    public IntelReport {
        if (reportId == null || reportId.isBlank()) {
            throw new IllegalArgumentException("reportId must not be blank");
        }
        if (query == null || query.isBlank()) {
            throw new IllegalArgumentException("query must not be blank");
        }
        if (htmlContent == null || htmlContent.isBlank()) {
            throw new IllegalArgumentException("htmlContent must not be blank");
        }
        if (userEmail == null || userEmail.isBlank()) {
            throw new IllegalArgumentException("userEmail must not be blank");
        }
        if (generatedAt == null) {
            throw new IllegalArgumentException("generatedAt must not be null");
        }
        if (sources == null) {
            sources = List.of();
        }
    }
}
