package com.wgblackmon.aihealthcare.domain.model;

import java.time.Instant;

/**
 * Immutable domain record representing a pre-generated AI summary for a
 * topic section on the news listing page.
 *
 * <p>Each topic with more than one harvested article receives a concise
 * summary generated during the feed harvest cycle.  The summary is stored
 * in the database and served statically on page load to avoid repeated AI
 * API calls.
 *
 * <p>The {@code topic} field matches the topic name used in
 * {@link com.wgblackmon.aihealthcare.domain.port.outbound.ArticleIngestionPort}
 * and the news listing configuration, serving as the natural key.
 *
 * <p>Summaries generated by the anti-slop pipeline set {@code pipelineVersion}
 * to a non-null string (e.g. {@code "anti-slop-v1"}).  Legacy summaries have
 * {@code null} for both quality fields; use {@link #isAntiSlop()} to distinguish.
 *
 * @param topic           Topic name (e.g. "Anthropic Healthcare"); must not be blank.
 * @param summaryText     AI-generated summary prose; must not be blank.
 * @param generatedAt     Timestamp when the summary was generated; must not be null.
 * @param pipelineVersion Pipeline that produced this summary; null for legacy rows.
 * @param lintScore       SlopLinter score 0–100; null for legacy rows.
 *
 * @author  Bill Blackmon
 * @version 1.1
 * @since   2026-05-21
 * @updated 2026-09-29
 */
public record TopicSummary(String topic, String summaryText, Instant generatedAt,
                            String pipelineVersion, Integer lintScore) {

    /**
     * Compact constructor — validates required fields.
     * {@code pipelineVersion} and {@code lintScore} are nullable for backward compatibility.
     */
    public TopicSummary {
        if (topic == null || topic.isBlank()) {
            throw new IllegalArgumentException("topic must not be blank");
        }
        if (summaryText == null || summaryText.isBlank()) {
            throw new IllegalArgumentException("summaryText must not be blank");
        }
        if (generatedAt == null) {
            throw new IllegalArgumentException("generatedAt must not be null");
        }
    }

    /** Returns {@code true} when this summary was generated by the anti-slop pipeline. */
    public boolean isAntiSlop() {
        return pipelineVersion != null && !pipelineVersion.isBlank();
    }
}
