package com.wgblackmon.aihealthcare.domain.port.outbound;

import java.time.LocalDate;
import java.util.Optional;

/**
 * Outbound port for reading daily article summary files generated by the
 * NotebookLM export pipeline.
 *
 * <p>Implementations read date-stamped summary files from the configured
 * summaries directory.  The domain layer uses these summaries to build
 * the FREE-tier daily digest newsletter.
 *
 * @author  Bill Blackmon
 * @version 1.0
 * @since   2026-07-20
 * @updated 2026-07-21
 */
public interface DailySummaryPort {

    /**
     * Returns the HTML summary for the given date, if one exists.
     *
     * @param date The date to look up (maps to {@code yyyy_MM_dd.html}).
     * @return The HTML content, or empty if no file exists for that date.
     */
    Optional<String> getHtmlSummary(LocalDate date);

    /**
     * Returns the plain-text summary for the given date, if one exists.
     *
     * @param date The date to look up (maps to {@code yyyy_MM_dd.txt}).
     * @return The text content, or empty if no file exists for that date.
     */
    Optional<String> getTextSummary(LocalDate date);

    /**
     * Returns the most recent date for which an HTML summary file exists,
     * searching backwards from today up to a configurable lookback window.
     *
     * @return The most recent summary date, or empty if none found.
     */
    Optional<LocalDate> findMostRecentSummaryDate();
}
